# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Free Trial(d039de35-d35a-4bfe-8640-5789615ea505)'
    subscriptionId: 'd039de35-d35a-4bfe-8640-5789615ea505'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Deploy-RG-01'
    location: 'East US'
    templateLocation: 'Linked artifact'
    deploymentMode: 'Incremental'